version: '3.4'

services:
  hbdb:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management

  hb.catalog:
    image: ${DOCKER_REGISTRY-}hbcatalog
    build:
      context: .
      dockerfile: Services/Catalog/Hb.Catalog/Dockerfile
