version: '3.4'

services:
  hbdb:
    image: mongo

  hb-redis:
    image: redis:alpine

  hb.catalog:
    image: ${DOCKER_REGISTRY-}hbcatalog
    build:
      context: .
      dockerfile: Services/Catalog/Hb.Catalog/Dockerfile
